### ISSUE TITLE
subporcess issue when running the test yolo code 

### ISSUE THREAD

**Issue by mo7mmed77** [shizukachan/darknet-nnpack#26]
Hello there

I just started recently learning about YOLO and how to implement it and hopefully contribute to improve it. 

I tried running the darknet-nnpack procedures and everything was okay until when i tried to test the python code rpi_record.py, then I ran into the following error:-

I'm running python 2.7.16 

pi@raspberrypi:~/darknet-nnpack $ sudo python rpi_record.py 
Traceback (most recent call last):
  File "rpi_record.py", line 26, in <module>
    stdin = PIPE, stdout = PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Could you please help to fix this issue. BTW I'm capturing an image everytime i run the code (in the directory only). Also, I'm using raspberry pi camera v2.

**Comment by mo7mmed77** [comment]
I fixed the issue. 

it turns out i needed to make an excutable for the darknet file that is in the examples. 

right now the code is running but it says there's an error  

"
('Error:', AttributeError("'NoneType' object has no attribute 'shape'",))
get Enter Image Path: 
"

**Comment by mo7mmed77** [comment]
In some cases I'm getting "Segmentation Fault', Could someone please tell me what could be the issue here.?
